-- begin COR_NEIGHBORHOOD
alter table COR_NEIGHBORHOOD add constraint FK_COR_NEIGHBORHOOD_ON_CITY foreign key (CITY_ID) references COR_CITY(ID);
create index IDX_COR_NEIGHBORHOOD_ON_CITY on COR_NEIGHBORHOOD (CITY_ID);
-- end COR_NEIGHBORHOOD

-- begin COR_CITY
alter table COR_CITY add constraint FK_COR_CITY_ON_DEPARTMENT foreign key (DEPARTMENT_ID) references COR_DEPARTMENT(ID);
alter table COR_CITY add constraint FK_COR_CITY_ON_COUNTRY foreign key (COUNTRY_ID) references COR_COUNTRY(ID);
create unique index IDX_COR_CITY_UK_CODE on COR_CITY (CODE) where DELETE_TS is null;
create index IDX_COR_CITY_ON_DEPARTMENT on COR_CITY (DEPARTMENT_ID);
create index IDX_COR_CITY_ON_COUNTRY on COR_CITY (COUNTRY_ID);
-- end COR_CITY

--begin COR_COUNTRY
create unique index IDX_COR_COUNTRY_UK_ISO_ALPHA3_CODE on COR_COUNTRY (ISO_ALPHA3_CODE) where DELETE_TS is null;
--end COR_COUNTRY


--begin COR_DEPARTMENT
alter table COR_DEPARTMENT add constraint FK_COR_DEPARTMENT_ON_COUNTRY foreign key (COUNTRY_ID) references COR_COUNTRY(ID);
create unique index IDX_COR_DEPARTMENT_UK_CODE on COR_DEPARTMENT (CODE) where DELETE_TS is null;
create index IDX_COR_DEPARTMENT_ON_COUNTRY on COR_DEPARTMENT (COUNTRY_ID);
--end COR_DEPARTMENT

-- begin COR_DOCUMENT
alter table COR_DOCUMENT add constraint FK_COR_DOCUMENT_ON_DOCUMENT_TYPE foreign key (DOCUMENT_TYPE_ID) references COR_DOCUMENT_TYPE(ID);
alter table COR_DOCUMENT add constraint FK_COR_DOCUMENT_ON_COUNTRY foreign key (COUNTRY_ID) references COR_COUNTRY(ID);
alter table COR_DOCUMENT add constraint FK_COR_DOCUMENT_ON_PERSON foreign key (PERSON_ID) references COR_PERSON(ID);
create unique index IDX_COR_DOCUMENT_UNQ on COR_DOCUMENT (DOCUMENT_NUMBER, DOCUMENT_TYPE_ID) where DELETE_TS is null;
create index IDX_COR_DOCUMENT_ON_DOCUMENT_TYPE on COR_DOCUMENT (DOCUMENT_TYPE_ID);
create index IDX_COR_DOCUMENT_ON_COUNTRY on COR_DOCUMENT (COUNTRY_ID);
create index IDX_COR_DOCUMENT_ON_PERSON on COR_DOCUMENT (PERSON_ID);
-- end COR_DOCUMENT


-- begin COR_CURRENCY
alter table COR_CURRENCY add constraint FK_COR_CURRENCY_ON_COUNTRY foreign key (COUNTRY_ID) references COR_COUNTRY(ID);
create unique index IDX_COR_CURRENCY_UK_SYMBOL on COR_CURRENCY (SYMBOL) where DELETE_TS is null;
create unique index IDX_COR_CURRENCY_UK_CODE on COR_CURRENCY (CODE) where DELETE_TS is null;
create unique index IDX_COR_CURRENCY_UK_CODE_ISO on COR_CURRENCY (CODE_ISO) where DELETE_TS is null;
create index IDX_COR_CURRENCY_ON_COUNTRY on COR_CURRENCY (COUNTRY_ID);
-- end COR_CURRENCY


-- begin COR_PERSON_RELATION
alter table COR_PERSON_RELATION add constraint FK_COR_PERSON_RELATION_ON_PERSON foreign key (PERSON_ID) references COR_PERSON(ID);
alter table COR_PERSON_RELATION add constraint FK_COR_PERSON_RELATION_ON_RELATED_PERSON foreign key (RELATED_PERSON_ID) references COR_PERSON(ID);
alter table COR_PERSON_RELATION add constraint FK_COR_PERSON_RELATION_ON_RELATION_TYPE foreign key (RELATION_TYPE_ID) references COR_PERSON_RELATION_TYPE(ID);
create unique index IDX_COR_PERSON_RELATION_UNQ on COR_PERSON_RELATION (PERSON_ID, RELATED_PERSON_ID) where DELETE_TS is null;
create index IDX_COR_PERSON_RELATION_ON_PERSON on COR_PERSON_RELATION (PERSON_ID);
create index IDX_COR_PERSON_RELATION_ON_RELATED_PERSON on COR_PERSON_RELATION (RELATED_PERSON_ID);
create index IDX_COR_PERSON_RELATION_ON_RELATION_TYPE on COR_PERSON_RELATION (RELATION_TYPE_ID);
-- end COR_PERSON_RELATION


-- begin COR_PERSON
alter table COR_PERSON add constraint FK_COR_PERSON_ON_NATIONALITY foreign key (NATIONALITY_ID) references COR_COUNTRY(ID);
create index IDX_COR_PERSON_ON_NATIONALITY on COR_PERSON (NATIONALITY_ID);
-- end COR_PERSON


-- begin COR_PHYSICAL_PERSON
alter table COR_PHYSICAL_PERSON add constraint FK_COR_PHYSICAL_PERSON_ON_ID foreign key (ID) references COR_PERSON(ID) on delete CASCADE;

create index IDX_COR_PHYSICAL_PERSON_ON_GENDER on COR_PHYSICAL_PERSON (GENDER);
create index IDX_COR_PHYSICAL_PERSON_ON_MARITAL_STATUS on COR_PHYSICAL_PERSON (MARITAL_STATUS);
-- end COR_PHYSICAL_PERSON

-- begin COR_JURIDICAL_PERSON
alter table COR_JURIDICAL_PERSON add constraint FK_COR_JURIDICAL_PERSON_ON_ID foreign key (ID) references COR_PERSON(ID) on delete CASCADE;
create index IDX_COR_JURIDICAL_PERSON_ON_JURIDICAL_TYPE on COR_JURIDICAL_PERSON (JURIDICAL_TYPE);
-- end COR_JURIDICAL_PERSON


